In [61]:
import numpy as np
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt

In [63]:
# mv kaggle.json ~/.kaggle/kaggle.json
!kaggle datasets download -d tmdb/tmdb-movie-metadata

Dataset URL: https://www.kaggle.com/datasets/tmdb/tmdb-movie-metadata
License(s): other
Downloading tmdb-movie-metadata.zip to c:\Users\Nilay Kumar\Desktop\mre\Movie-Recommender-Engine

  0%|          | 0.00/8.89M [00:00<?, ?B/s]
 11%|█▏        | 1.00M/8.89M [00:01<00:09, 842kB/s]
 23%|██▎       | 2.00M/8.89M [00:01<00:04, 1.66MB/s]
 34%|███▍      | 3.00M/8.89M [00:02<00:03, 1.58MB/s]
 45%|████▌     | 4.00M/8.89M [00:02<00:02, 1.85MB/s]
 56%|█████▋    | 5.00M/8.89M [00:02<00:01, 2.38MB/s]
 68%|██████▊   | 6.00M/8.89M [00:03<00:01, 2.33MB/s]
 79%|███████▉  | 7.00M/8.89M [00:03<00:00, 2.34MB/s]
 90%|█████████ | 8.00M/8.89M [00:03<00:00, 2.69MB/s]
100%|██████████| 8.89M/8.89M [00:04<00:00, 2.49MB/s]
100%|██████████| 8.89M/8.89M [00:04<00:00, 2.12MB/s]

In [66]:
import zipfile

# Specify the path to your zip file and the destination directory
zip_path = 'tmdb-movie-metadata.zip'
extract_to = 'tmdb-movie-metadata'

# Create a ZipFile object and extract its contents
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_to)

print("Files extracted successfully!")

Files extracted successfully!

In [68]:
# Extracting the movies and credits dataset
movies_df=pd.read_csv("tmdb-movie-metadata/tmdb_5000_movies.csv") 
credits_df=pd.read_csv("tmdb-movie-metadata/tmdb_5000_credits.csv") 
movies_df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [69]:
# Checking the info of the movies dataset
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [70]:
#Not needed:
# (1)homepage
# (2)Original Language 
# (3)Revenue
# (5)Production Companies
# (6)Production Countries
# (7)Release Date
# (8)Runtime
# (9)Spoken Languages
# (10)Status
# (11)Budget
# (12)

In [71]:
# Needed
# (1)Original Title
# (2)Genres
# (5)Keywords 
# (6)Overview
# (7)Taglines
# (4)Vote Count
# (3)Vote Average 
# (8)Popularity

In [72]:
# Merge the two datasets on the 'id' column and drop the 'key_0' column
movies=movies_df.merge(credits_df,on=movies_df['id'])
movies.drop(['key_0'],axis=1,inplace=True)
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,spoken_languages,status,tagline,title_x,vote_average,vote_count,movie_id,title_y,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [73]:
# Drop the columns that are not needed
movies=movies[['id','title_x','genres','keywords','overview','cast','crew','vote_average','vote_count','production_companies']]
movies.head()

,id,title_x,genres,keywords,overview,cast,crew,vote_average,vote_count,production_companies
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",7.2,11800,"[{""name"": ""Ingenious Film Partners"", ""id"": 289..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",6.9,4500,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",6.3,4466,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam..."
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",7.6,9106,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""..."
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",6.1,2124,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]"

In [74]:
# Safety check for missing values
movies.isnull().sum()
movies.dropna(inplace=True)
# Check for duplicates
print("Number of Duplicated Rows",movies.duplicated().sum())

Number of Duplicated Rows 0

In [75]:
movies.head()

,id,title_x,genres,keywords,overview,cast,crew,vote_average,vote_count,production_companies
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",7.2,11800,"[{""name"": ""Ingenious Film Partners"", ""id"": 289..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",6.9,4500,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",6.3,4466,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam..."
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",7.6,9106,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""..."
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",6.1,2124,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]"

In [76]:
import json
# Extracting Companies
def extract_companies(obj):
  companies=[]
  df=json.loads(obj)
  for i in range(len(df)):
    companies.append(df[i]['name'])
  return companies

#Combining company names as one 
def wordize(obj):
  new_obj = []
  for i in range(len(obj)):
    new_obj.append(obj[i].replace(" ", ""))
  return new_obj

movies['production_companies']=movies['production_companies'].apply(extract_companies)
movies['production_companies']=movies['production_companies'].apply(wordize)

In [77]:
# EXTRACTING CAST NAMES
import json
def extract_names(obj):
  names=[]
  df=json.loads(obj)
  for i in range(len(df)):
    names.append(df[i]['name'])
  return names[0:4]

movies['cast']=movies['cast'].apply(extract_names)

In [78]:
# EXTRACTING KEYWORDS
def extract_keywords(obj):
  keywords=[]
  df=json.loads(obj)
  for i in range(len(df)):
    keywords.append(df[i]['name'])
  return keywords

movies['keywords']=movies['keywords'].apply(extract_keywords)

In [79]:
# EXTRACTING GENRES
def extract_genres(obj):
  genres=[]
  df=json.loads(obj)
  for i in range(len(df)):
    genres.append(df[i]['name'])
  return genres

movies['genres']=movies['genres'].apply(extract_genres)

In [80]:
# EXTRACTING DIRECTORS
def extract_director(obj):
  df=json.loads(obj)
  for i in range(len(df)):
    if df[i]['job']=="Director":
      return [df[i]['name']]

movies['crew']=movies['crew'].apply(extract_director)

In [81]:
movies.head()

,id,title_x,genres,keywords,overview,cast,crew,vote_average,vote_count,production_companies
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron],7.2,11800,"[IngeniousFilmPartners, TwentiethCenturyFoxFil..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski],6.9,4500,"[WaltDisneyPictures, JerryBruckheimerFilms, Se..."
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes],6.3,4466,"[ColumbiaPictures, Danjaq, B24]"
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan],7.6,9106,"[LegendaryPictures, WarnerBros., DCEntertainme..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton],6.1,2124,[WaltDisneyPictures]

In [82]:
# RENAMING COLUMNS
movies.rename(columns = {'title_x':'titles'}, inplace = True)
movies.rename(columns = {'crew':'directors'}, inplace = True)

In [83]:
# LISTIFYING OVERVIEW COLUMN
def listify(obj):
  return obj.split()

movies['overview']=movies['overview'].apply(listify)

In [84]:
# REMOVING SPACES IN COLUMNS BETWEEN WORDS 
movies['genres']=movies['genres'].apply(wordize)
movies['keywords']=movies['keywords'].apply(wordize)
movies['cast']=movies['cast'].apply(wordize)

In [85]:
movies.head()

,id,titles,genres,keywords,overview,cast,directors,vote_average,vote_count,production_companies
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[James Cameron],7.2,11800,"[IngeniousFilmPartners, TwentiethCenturyFoxFil..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[Gore Verbinski],6.9,4500,"[WaltDisneyPictures, JerryBruckheimerFilms, Se..."
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bond’s, past, send...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[Sam Mendes],6.3,4466,"[ColumbiaPictures, Danjaq, B24]"
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[Christopher Nolan],7.6,9106,"[LegendaryPictures, WarnerBros., DCEntertainme..."
4,49529,John Carter,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[Andrew Stanton],6.1,2124,[WaltDisneyPictures]

In [86]:
# CREATING THE FINAL TAG COLUMN 
movies['tags']=movies['genres']+movies['keywords']+movies['overview']+movies['cast']+movies['directors']+movies['production_companies']

In [87]:
# REMOVING OTHER COLUMNS
movies.drop(['genres','keywords','overview','cast','directors','vote_average','vote_count','production_companies'],axis=1,inplace=True)

In [88]:
movies.dropna(inplace=True)
movies.reset_index(inplace = True, drop=True)
movies

,id,titles,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction, c..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action, ocean, drugabuse,..."
2,206647,Spectre,"[Action, Adventure, Crime, spy, basedonnovel, ..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller, dccomics, cri..."
4,49529,John Carter,"[Action, Adventure, ScienceFiction, basedonnov..."
...,...,...,...
4765,9367,El Mariachi,"[Action, Crime, Thriller, unitedstates–mexicob..."
4766,72766,Newlyweds,"[Comedy, Romance, A, newlywed, couple's, honey..."
4767,231617,"Signed, Sealed, Delivered","[Comedy, Drama, Romance, TVMovie, date, loveat..."
4768,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4769,25975,My Date with Drew,"[Documentary, obsession, camcorder, crush, dre..."

In [89]:
def sentenize(obj):
  sentence= " ".join(obj)
  return sentence

movies['tags']=movies['tags'].apply(sentenize)

In [90]:
# Removing Similar Words using Stemming
import nltk 
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()


# Applying Stemming to all the Sentences
def stem(text):
  y=[]
  for i in text.split():
    y.append(ps.stem(i))
  return " ".join(y)


# Removing all Similar words using Stemming
movies['tags']=movies['tags'].apply(stem)

In [91]:
movies.head()

,id,titles,tags
0,19995,Avatar,action adventur fantasi sciencefict culturecla...
1,285,Pirates of the Caribbean: At World's End,adventur fantasi action ocean drugabus exotici...
2,206647,Spectre,action adventur crime spi basedonnovel secreta...
3,49026,The Dark Knight Rises,action crime drama thriller dccomic crimefight...
4,49529,John Carter,action adventur sciencefict basedonnovel mar m...

In [92]:
# CONVERTING SENTENCES TO VECTORS USIGN BAG OF WORDS
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=9000,stop_words='english')
vectors=cv.fit_transform(movies['tags']).toarray()

In [93]:
vectors.shape

(4770, 9000)

In [94]:
# Checking out the most frequent features/words
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zoëkravitz', 'zucker', 'zwick'],
      dtype=object)

In [95]:
# Cosine Similarity finds the cosine distance with every movie
# Which is why all the diagonals are 1, since a movie is same as compared to itself
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(vectors)
similarity

array([[1.        , 0.06625892, 0.06882472, ..., 0.0381385 , 0.        ,
        0.        ],
       [0.06625892, 1.        , 0.05066946, ..., 0.02105847, 0.        ,
        0.0218687 ],
       [0.06882472, 0.05066946, 1.        , ..., 0.02187393, 0.04456565,
        0.        ],
       ...,
       [0.0381385 , 0.02105847, 0.02187393, ..., 1.        , 0.03704339,
        0.03776275],
       [0.        , 0.        , 0.04456565, ..., 0.03704339, 1.        ,
        0.0769373 ],
       [0.        , 0.0218687 , 0.        , ..., 0.03776275, 0.0769373 ,
        1.        ]])

In [96]:
similarity.shape

(4770, 4770)

In [97]:
def recommend(movie,num):
  movie_index=movies[movies['titles']==movie].index[0]
  distances=similarity[movie_index]
  movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:num]
  
  for i in movies_list:
    print(movies.iloc[i[0]].titles)

# Testing the Recommendation System
recommend('Spider-Man',10)

Spider-Man 3
Spider-Man 2
The Amazing Spider-Man 2
Arachnophobia
The Amazing Spider-Man
21 Jump Street
X-Men
Eight Legged Freaks
Kick-Ass

In [99]:
import pickle 
import os
os.mkdir('model_files')
pickle.dump(similarity,open('model_files/similarity.pkl','wb'))
pickle.dump(movies.to_dict(),open('model_files/movie_dict.pkl','wb'))